
import org.uci.spacifyLib.dto.RulesTBDeleted;
global org.uci.spacifyLib.dto.RulesTBDeleted ruleObj;

dialect  "mvel"

rule "occupancy rule"
    when
        RulesTBDeleted( calculatedValue1 > thresholdValue1 )
    then

        ruleObj.setTotalCredits(ruleObj.getTotalCredits() + ruleObj.getIncentive());
end

rule "duration rule"
    when
        RulesTBDeleted( calculatedValue2 > thresholdValue2 )
    then

        ruleObj.setTotalCredits(ruleObj.getTotalCredits() + ruleObj.getIncentive());
end
